Add MAINTAINERS.rst file
vmware/repository-service-tuf-worker pull request #208
Opened 2023-02-21 14:56 UTC by MVrachev

Add MAINTAINERS.rst file

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

2023-02-21 15:05 UTC, kairoaraujo requested changes

2023-02-21 15:05 UTC, kairoaraujo commented on MAINTAINERS.rst
> +GitHub username: @@lukpueh
```suggestion
GitHub username: @lukpueh
```

2023-02-21 17:09 UTC, rdimitrov approved these changes

2023-02-21 18:46 UTC, kairoaraujo approved these changes

2023-02-22 08:02 UTC, lukpueh approved these changes

2023-02-22 08:44 UTC, merged