fix: Add bump for Targets role
vmware/repository-service-tuf-worker pull request #255
Opened 2023-04-13 07:12 UTC by kairoaraujo

As RSTUF now uses the online key for Targets role, in this commit, we add the bump of Targets role.

* It renames the bump_bins_roles to bump_targets_roles
* It now bumps all Targets roles types, including Targets and its Delegated Roles bins

It guarantees that the target's role is automatically bumped before expiring, as we do for all roles which use online keys.

Closes #254

2023-04-13 18:03 UTC, MVrachev requested changes

2023-04-14 13:21 UTC, MVrachev commented on repository_service_tuf_worker/repository.py
> +                targets_meta.append((Targets.type, targets.signed.version))
I created such an issue: https://github.com/vmware/repository-service-tuf-worker/issues/262

2023-04-14 13:23 UTC, MVrachev submitted a review, later dismissed

2023-04-14 13:23 UTC, MVrachev commented
Could you fix the linting and we will merge it?

2023-04-14 13:33 UTC, kairoaraujo commented
> Could you fix the linting and we will merge it?

I rebased it.

2023-04-14 13:40 UTC, MVrachev approved these changes

2023-04-14 13:40 UTC, merged